exclusions = [
    # https://github.com/advisories/GHSA-g98v-hv3f-hcfr
    "atty",
]

additions = [
    # Crates that the compiler recommends
    # rg 'https://crates.io/crates/[a-z_-]+' \
    #   --glob '**/tests/**/*.stderr' \
    #   --glob 'compiler/rustc_error_codes/**/*.md' \
    #   --only-matching \
    #   --no-line-number \
    #   --no-filename \
    #   | sort \
    #   | uniq \
    #   | cut -d '/' -f 5
    "async-trait",
    "once_cell",
    "sptr",
    # Crate that The Rust Programming Language book uses
    "trpl",
]
